version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: spring-boot-postgres-db-learning-tutorial
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: admin
    ports:
        - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
volumes:
    postgres-db-data: